*** Makefile.orig	Wed Oct  4 08:33:48 2023
--- Makefile	Wed Oct  4 08:32:02 2023
***************
*** 321,327 ****
  MODULE_NIS_LDFLAGS=
  MODULE_READLINE_STATE=yes
  MODULE_READLINE_CFLAGS=
! MODULE_READLINE_LDFLAGS=-lreadline
  MODULE__SQLITE3_STATE=yes
  MODULE__SQLITE3_CFLAGS= -I$(srcdir)/Modules/_sqlite
  MODULE__SQLITE3_LDFLAGS=-lsqlite3
--- 321,327 ----
  MODULE_NIS_LDFLAGS=
  MODULE_READLINE_STATE=yes
  MODULE_READLINE_CFLAGS=
! MODULE_READLINE_LDFLAGS=-lreadline -rpath $(BUILD_RPATH)
  MODULE__SQLITE3_STATE=yes
  MODULE__SQLITE3_CFLAGS= -I$(srcdir)/Modules/_sqlite
  MODULE__SQLITE3_LDFLAGS=-lsqlite3
***************
*** 333,352 ****
  MODULE__UUID_LDFLAGS=
  MODULE_ZLIB_STATE=yes
  MODULE_ZLIB_CFLAGS=
! MODULE_ZLIB_LDFLAGS=-lz
  MODULE_BINASCII_STATE=yes
  MODULE_BINASCII_CFLAGS=-DUSE_ZLIB_CRC32 
! MODULE_BINASCII_LDFLAGS=-lz
  MODULE__BZ2_STATE=yes
  MODULE__BZ2_CFLAGS=
  MODULE__BZ2_LDFLAGS=-lbz2
  MODULE__LZMA_STATE=missing
  MODULE__SSL_STATE=yes
  MODULE__SSL_CFLAGS=-I/Users/culler/programs/frameworks/Python-3.12/../Frameworks/OpenSSL.framework/Versions/Current/include
! MODULE__SSL_LDFLAGS=-L/Users/culler/programs/frameworks/Python-3.12/../Frameworks/OpenSSL.framework/Versions/Current/lib  -lssl -lcrypto
  MODULE__HASHLIB_STATE=yes
  MODULE__HASHLIB_CFLAGS=-I/Users/culler/programs/frameworks/Python-3.12/../Frameworks/OpenSSL.framework/Versions/Current/include
! MODULE__HASHLIB_LDFLAGS=-L/Users/culler/programs/frameworks/Python-3.12/../Frameworks/OpenSSL.framework/Versions/Current/lib   -lcrypto
  MODULE__TESTCAPI_STATE=yes
  MODULE__TESTCLINIC_STATE=yes
  MODULE__TESTINTERNALCAPI_STATE=yes
--- 333,352 ----
  MODULE__UUID_LDFLAGS=
  MODULE_ZLIB_STATE=yes
  MODULE_ZLIB_CFLAGS=
! MODULE_ZLIB_LDFLAGS=-lz -rpath $(BUILD_RPATH)
  MODULE_BINASCII_STATE=yes
  MODULE_BINASCII_CFLAGS=-DUSE_ZLIB_CRC32 
! MODULE_BINASCII_LDFLAGS=-lz -rpath $(BUILD_RPATH)
  MODULE__BZ2_STATE=yes
  MODULE__BZ2_CFLAGS=
  MODULE__BZ2_LDFLAGS=-lbz2
  MODULE__LZMA_STATE=missing
  MODULE__SSL_STATE=yes
  MODULE__SSL_CFLAGS=-I/Users/culler/programs/frameworks/Python-3.12/../Frameworks/OpenSSL.framework/Versions/Current/include
! MODULE__SSL_LDFLAGS=-L/Users/culler/programs/frameworks/Python-3.12/../Frameworks/OpenSSL.framework/Versions/Current/lib  -lssl -lcrypto -rpath $(BUILD_RPATH)
  MODULE__HASHLIB_STATE=yes
  MODULE__HASHLIB_CFLAGS=-I/Users/culler/programs/frameworks/Python-3.12/../Frameworks/OpenSSL.framework/Versions/Current/include
! MODULE__HASHLIB_LDFLAGS=-L/Users/culler/programs/frameworks/Python-3.12/../Frameworks/OpenSSL.framework/Versions/Current/lib   -lcrypto -rpath $(BUILD_RPATH)
  MODULE__TESTCAPI_STATE=yes
  MODULE__TESTCLINIC_STATE=yes
  MODULE__TESTINTERNALCAPI_STATE=yes
