name: py2app framework

on: [push]

jobs:
  build_wheels:
    name: Build Framework for py2app
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          DEV_ID: ${{ secrets.DEV_ID }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # Create file needed for make
          echo $DEV_ID > DEV_ID.txt

      - name: Install macher
        run: |
          wget https://github.com/culler/macher/releases/latest/download/macher
          chmod +x macher
          mv macher /usr/local/bin
          
      - name: Build Zlib
        run: |
          make Setup Zlib

      - name: Build Readline
        run: |
          make Readline

      - name: Build OpenSSL
        run: |
          make OpenSSL

      # There is some delay in mirroring to github from the actual
      # fossil repo.  Can change to "fossil_tcltk.sh" if need the very
      # latest, but this is much slower.
      - name: Fetch TclTk source
        run: >
          cd TclTk &&
          bash git_tcltk.sh

      - name: Build TclTk
        run: |
          make TclTk

      #- name: Build Python
      #  run: |
      #    make FOR_PY2APP=yes Python
      #
      #- name: Sign everything
      #  run: |
      #    make Sign

      - name: Assemble tarball
        run: |
          make Tarball

      - uses: actions/upload-artifact@v2
        with:
          name: Frameworks.tgz
          path: ./Frameworks.tgz
